### ISSUE TITLE
CONFIG_INTEL_PMC_CORE is not set on Debian config

### ISSUE THREAD

**Issue by kitakar5525** [qzed/linux-surface-kernel-configs#1]
From jakeday/linux-surface#571

>>OK. But it's still weird. package_cstate_show and slp_s0_residency_usec should exist.
>
>It doesn't show because qzed's debian kernel is not compiled with CONFIG_INTEL_PMC_CORE enabled.
>
>https://github.com/qzed/linux-surface-kernel-configs/blob/v5.2/debian-5.2-x86_64.config#L7326

Can you please enable the config on Debian config, too? (CONFIG_INTEL_PMC_CORE=m or =y).
(Arch config has CONFIG_INTEL_PMC_CORE=y)

By the way, Debian disabled the config by default? then, we may want to consider using Ubuntu config instead.

**Comment by qzed** [comment]
@kitakar5525 I can do that. Yes, looks like Debian disabled that by default. I've just taken their config and added the relevant surface specific options. Might have a look at Ubuntu in the future.

**Comment by qzed** [comment]
I've updated the config files, but I'm not sure when I'm able to compile/release some new kernels. Might take me a bit.

**Comment by kitakar5525** [comment]
OK, Thank you!
